name: User Story
description: Template for creating user stories
labels: ["story"]
body:
  - type: input
    id: title
    attributes:
      label: Story Title
      placeholder: "As a [user], I want [goal] so that [benefit]"
    validations:
      required: true
  - type: textarea
    id: user-story
    attributes:
      label: User Story
      description: Describe the user story in detail
      placeholder: "As a [user], I want [goal] so that [benefit]"
    validations:
      required: true
  - type: textarea
    id: acceptance-criteria
    attributes:
      label: Acceptance Criteria
      description: List the conditions that must be met
      placeholder: "- Criteria 1\n- Criteria 2"
    validations:
      required: true
  - type: dropdown
    id: service-framework
    attributes:
      label: Service Framework
      options:
        - NestJS
        - Fastify
        - Other
    validations:
      required: true
  - type: input
    id: repository-url
    attributes:
      label: Repository URL
      placeholder: "https://github.com/Vaultody-com/repo-name"
  - type: textarea
    id: performance-criteria
    attributes:
      label: Performance Acceptance Criteria
      description: Describe any performance requirements
      placeholder: "e.g. API response time < 200ms"
  - type: dropdown
    id: agent-owner
    attributes:
      label: Agent Owner
      options:
        - Developer
        - Unit
        - Integration
        - Performance
        - Reviewer
        - QA
        - Team Leader
    validations:
      required: true
  - type: input
    id: story-points
    attributes:
      label: Story Points
      placeholder: "1, 2, 3, 5, 8, 13"
